// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkA6Ng3GxmEFrclRUc7sDQr1fmXlqsNOA',
    appId: '1:358822892005:web:133ae7c8a5c80eeb27df0c',
    messagingSenderId: '358822892005',
    projectId: 'tripai-46fbb',
    authDomain: 'tripai-46fbb.firebaseapp.com',
    storageBucket: 'tripai-46fbb.firebasestorage.app',
    measurementId: 'G-Z24YQBP4EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBba1cOBaM9ShzwAhkOFGgxxqdhjfaYPC0',
    appId: '1:358822892005:android:f16b67fa0d92319f27df0c',
    messagingSenderId: '358822892005',
    projectId: 'tripai-46fbb',
    storageBucket: 'tripai-46fbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm_tbJk1j5mLFWHBTBtqsMRBekJMfaSbE',
    appId: '1:358822892005:ios:5ad467f9ea22006f27df0c',
    messagingSenderId: '358822892005',
    projectId: 'tripai-46fbb',
    storageBucket: 'tripai-46fbb.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm_tbJk1j5mLFWHBTBtqsMRBekJMfaSbE',
    appId: '1:358822892005:ios:5ad467f9ea22006f27df0c',
    messagingSenderId: '358822892005',
    projectId: 'tripai-46fbb',
    storageBucket: 'tripai-46fbb.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkA6Ng3GxmEFrclRUc7sDQr1fmXlqsNOA',
    appId: '1:358822892005:web:bdf68735073733a827df0c',
    messagingSenderId: '358822892005',
    projectId: 'tripai-46fbb',
    authDomain: 'tripai-46fbb.firebaseapp.com',
    storageBucket: 'tripai-46fbb.firebasestorage.app',
    measurementId: 'G-0PWHYD0E7D',
  );

}